.scripts/docker-build-router.sh, Makefile, README.md, docker-compose.managed.yml, docker-compose.otel-collector.yml, docker-compose.otel-zipkin.yml, docker-compose.router-otel.yml, docker-compose.router.yml, docker-compose.yml, router/Dockerfile, router/configuration.yaml, router/install.sh, router/run.sh
=> add router

.github/workflows/main-router.yml, .scripts/smoke-router.sh, Makefile, README.md
=> add router CI

Makefile, router/configuration.yaml
=> update router otel config

router/run.sh
=> enable router tracing

router/run.sh
=> disable router trace logging

router/configuration.yaml
Router 0.1.0-alpha.2 ships with a new configuration.yml schema, when it comes to tracing / exporters setup.
This commit updates updates the configuration.yml file accodringly.
=> fix: Update router configuration.

Makefile
Cleanup Makefile:
- docker-up uses docker-up-local
=> cleanup Makefile

Makefile, README.md
=> link to apollo router using Fed 1 in supergraph-demo

Makefile
=> router demo runs smoke tests

router/Dockerfile
=> use STOPSIGNAL SIGINT for Apollo Router

.scripts/smoke.sh, .scripts/subgraphs.sh, docker-compose.managed.yml, docker-compose.otel-collector.yml, docker-compose.otel-zipkin.yml, docker-compose.router-otel.yml, docker-compose.router.yml, docker-compose.yml, subgraphs/inventory/inventory.js, subgraphs/inventory/package.json, subgraphs/pandas/Dockerfile, subgraphs/pandas/package.json, subgraphs/pandas/pandas.graphql, subgraphs/pandas/pandas.js, subgraphs/products/package.json, subgraphs/products/products.js, subgraphs/users/package.json, subgraphs/users/users.js, supergraph.graphql, supergraph.yaml
=> federate standard graphql pandas service

renovate.json
=> automerge minor dependencies

gateway/package.json
=> remove old federation lib

opentelemetry/collector-config.yml
=> remove cors

docker-compose.otel-collector.yml, docker-compose.router-otel.yml, gateway/package.json, renovate.json, subgraphs/inventory/package.json, subgraphs/products/package.json, subgraphs/users/package.json
- Fixes: https://github.com/apollographql/federation/issues/1500
=> bump to otel 1.0

gateway/package.json
=> slim down gateway deps

router/configuration.yaml
- for https://github.com/apollographql/router/issues/606
=> router plugins for otel

.github/workflows/main-router.yml, .github/workflows/main.yml, .github/workflows/managed.yml, Makefile, subgraphs/inventory/Dockerfile
=> inventory subgraph separate gradle deps/build/run

subgraphs/inventory/Dockerfile
=> pull gradle deps only for build 1st pass

supergraph.graphql
=> updated supergraph with `@tag` composed from subgraph

Makefile, gateway/gateway.js, gateway/package.json
=> add usage reporting with `fieldLevelInstrumentation` at 1%

.github/workflows/main-router.yml, .github/workflows/main.yml, .github/workflows/managed.yml, .scripts/smoke.sh, Makefile, subgraphs/inventory/app/src/main/kotlin/inventory/Application.kt
=> Kotlin inline tracing for `fieldLevelInstrumentation`

Makefile
=> `make load` for generating latency distributions and usage reporting

.github/workflows/main-router.yml, .github/workflows/managed-router.yml, .github/workflows/managed.yml, Makefile, README.md, docker-compose.router-managed.yml, router/Dockerfile
- `make demo-router` uses managed federation like `make demo` for the Gateway
- updated readme
=> router with managed federation

.github/workflows/managed-router.yml
=> use ci-router variant for managed federation

docker-compose.router-otel.yml
=> router otel to use local supergraph schema

gateway/Dockerfile, router/Dockerfile, subgraphs/inventory/Dockerfile, subgraphs/pandas/Dockerfile, subgraphs/products/Dockerfile, subgraphs/users/Dockerfile
=> use debian bullseye for all docker images

.scripts/smoke.sh
=> load test timing

README.md
=> add router otel docs

gateway/Dockerfile, gateway/package.json, subgraphs/pandas/Dockerfile, subgraphs/products/Dockerfile, subgraphs/products/package.json, subgraphs/users/Dockerfile, subgraphs/users/package.json
=> bump otel lib

.scripts/smoke.sh
=> add apollographql-client-name for smoke tests

router/Dockerfile
=> fix #116 - router fails on M1

docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router/router.yaml
=> use prebuilt router docker image

router.yaml, router/acme_router.yaml
=> add scheme to otel config

README.md
=> readme update for custom router plugin

router/Dockerfile
=> Dockerfile update for custom router plugins

.github/workflows/main-router-custom.yml, .github/workflows/main-router.yml, .github/workflows/main.yml, .github/workflows/managed-router.yml, .github/workflows/managed.yml, README.md
=> use latest rover

docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router/Cargo.toml
=> bump to router v0.9.0-rc.0

docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router/Cargo.lock, router/Cargo.toml, router/src/hello_world.rs
=> update to router GA (0.9.0) release

.scripts/smoke.sh, subgraphs/products/products.graphql, supergraph.graphql
=> `@inaccessible` in subgraphs to hide fields in API schema

docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router.yaml, router/custom-image/acme_router.yaml, router/custom-plugin/acme_router.yaml
=> update to new Router 1.0 config format

Makefile, README.md, router/custom-plugin/.gitignore, router/custom-plugin/Cargo.toml, router/custom-plugin/Dockerfile, router/custom-plugin/localhost/.gitignore, router/custom-plugin/localhost/compose.sh, router/custom-plugin/localhost/router.yaml, router/custom-plugin/localhost/supergraph.graphql, router/custom-plugin/localhost/supergraph.yaml, router/custom-plugin/src/hello_world.rs
=> router 1.0 native plugin example

Makefile, docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router/custom-plugin/Cargo.toml
=> bump to router-v1.0.0-alpha.2

.scripts/smoke-defer.sh
=> defer smoke tests showing incremental delivery

subgraphs/reviews/app.py, subgraphs/reviews/pdm.lock, subgraphs/reviews/pyproject.toml
- Expose api at /
- Update strawberry
=> Expose reviews service at `/`

.scripts/smoke.sh, README.md, docker-compose.router-defer-ac.yml, docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, opentelemetry/router.yaml, router.yaml, router/custom-image/acme_router.yaml, router/custom-main/Cargo.toml, router/custom-main/Dockerfile, router/custom-main/localhost/router.yaml, router/custom-main/localhost/supergraph.graphql, router/custom-plugin/Cargo.toml, router/custom-plugin/Dockerfile, router/custom-plugin/localhost/router.yaml
`make run-router-main` followed by `make smoke` works!
=> Bump to router-1.0.0-rc.0

.github/workflows/managed-router-custom-main.yml, .scripts/graph-api-env.sh, .scripts/publish.sh, .scripts/subgraphs-localhost.sh, .scripts/up-router-main.sh, Makefile, docker-compose.router-custom-image.yml, docker-compose.router-custom-main-managed.yml, docker-compose.router-custom-main.yml, docker-compose.router-custom-plugin.yml, docker-compose.router-defer-ac.yml, docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router.yaml, router/custom-image/acme_router.yaml, router/custom-main/localhost/router.yaml, router/custom-main/localhost/supergraph.graphql
=> op trace support with ftv1 subgraph trace sampling

docker-compose.router-defer-ac.yml, docker-compose.router-managed.yml, docker-compose.router-otel.yml, opentelemetry/router.yaml, router.yaml, router/custom-image/acme_router.yaml, router/custom-main/localhost/router.yaml, router/custom-plugin/localhost/router.yaml
=> formatting fixes

docker-compose.local.yml, local.graphql
rebuilding the router under docker is time consuming for tests, and does not make debugging easy. This provides a configuration to run the tests with a router built and started locally
=> docker-compose and schema for usage with a locally run router

router/custom-main/Cargo.toml, router/custom-plugin/Cargo.toml
=> remove async-compression patch

.scripts/up-router-main.sh, Makefile
=> --dev mode for make run-router-main

.scripts/smoke-defer.sh, .scripts/smoke.sh, subgraphs/inventory/app/src/main/kotlin/inventory/GraphQLConfiguration.kt, subgraphs/products/products.graphql, subgraphs/products/products.js, subgraphs/users/users.js, supergraph.graphql
- adds delay for estimated delivery dates in inventory service for showcasing `@defer`
- updated product data to make query results look more interesting
=> estimated deliver dates to showcase defer and new product data

docker-compose.router-defer-ac.yml, docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, opentelemetry/router.yaml, router.yaml, router/custom-image/acme_router.yaml, router/custom-plugin/Cargo.toml, router/custom-plugin/localhost/router.yaml
=> bump to router-v1.0.0-rc.1

docker-compose.router-defer-ac.yml, docker-compose.router-managed.yml, docker-compose.router-otel.yml, docker-compose.router.yml, router/custom-plugin/Cargo.toml
=> bump to router-v1.0.0-rc.2

Makefile, README.md, examples/local/docker-compose.router-no-otel.yaml, examples/local/docker-compose.router-rhai.yaml, examples/local/docker-compose.router-rust-plugin.yaml, examples/studio/docker-compose.router-no-code.yaml, examples/studio/docker-compose.router-rhai.yaml, examples/studio/docker-compose.router-rust-plugin.yaml
=> add no-otel option

.scripts/docker-prune.sh, README.md
=> add inline fragment example for `@defer`

Makefile, examples/local/supergraph/dockerhost.graphql, examples/local/supergraph/localhost.graphql, supergraph/router.yaml
=> `make run-supergraph-no-dev` for running without `--dev` mode

.scripts/smoke.sh
=> add `accept` header for all smoke test queries

.github/workflows/local-router-no-code.yaml, .scripts/smoke.sh, subgraphs/inventory/app/src/main/resources/graphql/inventory.graphqls, subgraphs/products/package.json, subgraphs/products/products.graphql, subgraphs/products/products.js, supergraph/schema/docker.graphql, supergraph/schema/local.graphql
=> `@composeDirective` examples

supergraph/gateway/package.json
Update gateway/package.json to use `@apollo/server` v4.0.0 🎉
=> run gateway with as4 GA

client/defer/apollo-client/Dockerfile, misc/advanced/router-dev/Dockerfile, subgraphs/inventory/Dockerfile, subgraphs/pandas/Dockerfile, subgraphs/products/Dockerfile, subgraphs/users/Dockerfile, supergraph/gateway/Dockerfile, supergraph/router-rhai-script/Dockerfile, supergraph/router-rust-plugin/Dockerfile
- switch to bullseye-slim
- install protoc for router-dev
- cleanup
=> switch to bullseye-slim

.github/workflows/studio-router-rust-dev.yaml, Makefile
=> cleanup router dev build

client/defer/apollo-client/Dockerfile, misc/advanced/router-dev/Dockerfile, subgraphs/inventory/Dockerfile, subgraphs/pandas/Dockerfile, subgraphs/products/Dockerfile, subgraphs/users/Dockerfile, supergraph/gateway/Dockerfile, supergraph/router-rhai-script/Dockerfile, supergraph/router-rust-plugin/Dockerfile, supergraph/schema/docker.graphql, supergraph/schema/local.graphql
=> update to bookworm-slim
